# Generated by Django 4.1.3 on 2022-11-29 00:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='dia_semana',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curso',
            name='fecha_creacion',
            field=models.DateField(default=datetime.datetime(2022, 11, 28, 21, 37, 10, 282812)),
        ),
    ]
