# Generated by Django 4.1.3 on 2022-12-08 11:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0003_productos_alter_curso_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='fecha_creacion',
            field=models.DateField(default=datetime.datetime(2022, 12, 8, 8, 25, 25, 37810)),
        ),
    ]
