# Generated by Django 4.1.3 on 2022-12-08 12:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0004_alter_curso_fecha_creacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localidad', models.CharField(max_length=40)),
                ('tiempo_de_entrega', models.IntegerField()),
                ('calificacion', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='curso',
            name='fecha_creacion',
            field=models.DateField(default=datetime.datetime(2022, 12, 8, 9, 32, 18, 699267)),
        ),
    ]
