# Generated by Django 4.1.3 on 2023-01-02 21:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0008_alter_curso_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='fecha_creacion',
            field=models.DateField(default=datetime.datetime(2023, 1, 2, 18, 34, 35, 824214)),
        ),
    ]
